import { downloadBlob } from "../services/api.js";

/** Export a table object {columns, rows} as CSV. */
export function exportTableCSV(table, filename = "insightpilot-table.csv") {
  if (!table) return;
  const cols = table.columns;
  const esc = (v) => {
    const s = v == null ? "" : String(v);
    return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
  };
  const lines = [cols.map(esc).join(",")];
  for (const row of table.rows || []) {
    lines.push(cols.map((c) => esc(row[c])).join(","));
  }
  downloadBlob(new Blob([lines.join("\n")], { type: "text/csv;charset=utf-8" }), filename);
}

export function exportJSON(data, filename = "insightpilot-export.json") {
  downloadBlob(
    new Blob([JSON.stringify(data, null, 2)], { type: "application/json" }),
    filename
  );
}

/** Export an entire QueryResult as a human-readable Markdown report. */
export function exportReport(result, filename = "insightpilot-report.md") {
  const md = buildMarkdownReport(result);
  downloadBlob(new Blob([md], { type: "text/markdown;charset=utf-8" }), filename);
}

function buildMarkdownReport(result) {
  const lines = [];
  lines.push(`# InsightPilot AI — Analysis Report`);
  lines.push("");
  lines.push(`**Question:** ${result.question}`);
  lines.push(`**Intent:** ${result.plan?.intent} · **LLM mode:** ${result.llm_mode}`);
  lines.push(`**Confidence:** ${(result.confidence * 100).toFixed(0)}%`);
  lines.push(`**Execution time:** ${result.execution_time_ms} ms`);
  lines.push("");

  lines.push("## Answer");
  lines.push("");
  lines.push(`- **${result.answer?.label}** → **${result.answer?.value}**`);
  if (result.answer?.detail) lines.push(`- *${result.answer.detail}*`);
  for (const p of result.answer?.pairs || []) {
    lines.push(`- ${p.k}: ${p.v}`);
  }
  lines.push("");

  lines.push("## Execution Plan");
  lines.push("");
  for (const s of result.plan?.steps || []) {
    const mark = s.status === "completed" ? "✓" : s.status === "failed" ? "✕" : "·";
    lines.push(`- ${mark} **${s.action}** — ${s.description} ${Object.keys(s.params || {}).length ? `\`${JSON.stringify(s.params)}\`` : ""}`);
  }
  lines.push("");

  lines.push("## Validation");
  lines.push("");
  if (!result.validation?.issues?.length) {
    lines.push("No issues detected.");
  } else {
    for (const i of result.validation.issues) {
      lines.push(`- **[${i.severity}]** ${i.code} — ${i.message}`);
    }
  }
  lines.push("");

  lines.push("## Supporting Tables");
  lines.push("");
  for (const t of result.tables || []) {
    lines.push(`### ${t.tool}`);
    lines.push("");
    lines.push(tableToMarkdown(t.table));
    lines.push("");
  }

  lines.push("## Business Insight");
  lines.push("");
  lines.push(result.insight || result.text || "");
  if (result.recommendation) {
    lines.push("");
    lines.push(`**Recommendation:** ${result.recommendation}`);
  }
  lines.push("");
  lines.push("## Suggested Follow-ups");
  lines.push("");
  for (const f of result.follow_ups || []) {
    lines.push(`- ${f.question} _(${f.reason})_`);
  }
  lines.push("");
  lines.push("---");
  lines.push("*Generated by InsightPilot AI. All numbers computed by Pandas; no fabricated values.*");
  return lines.join("\n");
}

function tableToMarkdown(table) {
  if (!table || !table.columns?.length) return "_empty_";
  const cols = table.columns;
  const header = `| ${cols.join(" | ")} |`;
  const sep = `| ${cols.map(() => "---").join(" | ")} |`;
  const body = (table.rows || []).slice(0, 50).map((r) => {
    return `| ${cols.map((c) => (r[c] == null ? "" : String(r[c]))).join(" | ")} |`;
  });
  return [header, sep, ...body].join("\n");
}

/** Render a Plotly figure JSON to PNG and download it. */
export async function exportChartPNG(figure, filename = "insightpilot-chart.png") {
  try {
    const mod = await import("plotly.js-dist-min");
    const Plotly = mod.default || mod;
    const img = await Plotly.toImage(figure, {
      format: "png",
      width: 1100,
      height: 620,
      scale: 2,
    });
    downloadBlob(await (await fetch(img)).blob(), filename);
  } catch (e) {
    console.error("PNG export failed", e);
  }
}
