"""Shared Pydantic models used across the InsightPilot agent pipeline.

Every agent emits data conforming to these models so the frontend can render
the full Think -> Plan -> Act -> Verify -> Explain pipeline uniformly.
"""
from __future__ import annotations

from typing import Any, Dict, List, Literal, Optional

from pydantic import BaseModel, Field


# --------------------------------------------------------------------------- #
# Dataset intelligence
# --------------------------------------------------------------------------- #
class ColumnProfile(BaseModel):
    """Statistical profile of a single column in the dataset."""

    name: str
    dtype: str
    nullable: bool
    unique: Optional[int] = None
    missing: Optional[int] = None
    missing_pct: Optional[float] = None
    min: Optional[Any] = None
    max: Optional[Any] = None
    mean: Optional[float] = None
    median: Optional[float] = None
    std: Optional[float] = None
    top: Optional[Any] = None
    top_freq: Optional[int] = None
    category: str = Field(
        description="numeric | categorical | datetime | text | id | boolean | other"
    )
    outliers: int = 0
    outlier_upper: Optional[float] = None
    outlier_lower: Optional[float] = None


class BusinessMetric(BaseModel):
    """A detected KPI-style business metric."""

    column: str
    label: str
    kind: str = Field(description="revenue | profit | margin | growth | other")
    aggregate: str = "sum"


class DatasetProfile(BaseModel):
    """Full profile generated by the Dataset Intelligence Agent."""

    dataset_id: str
    filename: str
    rows: int
    columns: int
    memory_usage: str
    missing_total: int
    duplicate_rows: int
    numeric_columns: List[str] = []
    categorical_columns: List[str] = []
    date_columns: List[str] = []
    id_columns: List[str] = []
    possible_metrics: List[str] = []
    business_metrics: List[BusinessMetric] = Field(default_factory=list)
    quality_score: float = 0.0
    column_profiles: List[ColumnProfile] = []
    head: List[Dict[str, Any]] = Field(default_factory=list)
    sample_columns: List[str] = Field(default_factory=list)


# --------------------------------------------------------------------------- #
# Agent pipeline
# --------------------------------------------------------------------------- #
class PlanStep(BaseModel):
    """A single executable step in the agent's execution plan."""

    step: int
    action: str
    description: str
    params: Dict[str, Any] = Field(default_factory=dict)
    status: Literal["pending", "running", "completed", "skipped", "failed"] = "pending"
    result: Optional[Any] = None
    note: Optional[str] = None


class ExecutionPlan(BaseModel):
    """Structured plan produced by the Planner Agent."""

    intent: str
    question: str
    steps: List[PlanStep]
    tools: List[str] = Field(default_factory=list)
    reasoning: str = ""
    needs_clarification: bool = False
    clarification_message: str = ""
    clarification_options: List["ClarificationOption"] = Field(default_factory=list)


class ClarificationOption(BaseModel):
    """A resolvable option shown to the user when the plan is ambiguous."""

    label: str
    value: Dict[str, Any] = Field(default_factory=dict)
    description: str = ""


class ValidationIssue(BaseModel):
    """A single issue detected by the Validation Agent."""

    severity: Literal["error", "warning", "info"]
    code: str
    message: str
    suggested_fix: Optional[str] = None


class ValidationReport(BaseModel):
    """Output of the Validation Agent."""

    valid: bool
    issues: List[ValidationIssue] = Field(default_factory=list)
    corrections: List[str] = Field(default_factory=list)


class ChartSpec(BaseModel):
    """A resolved chart definition produced by the Visualization Agent."""

    chart_type: str
    title: str
    rationale: str
    plotly_json: Dict[str, Any]
    export_png_hint: str = "download"


class FollowUp(BaseModel):
    """A suggested follow-up question."""

    question: str
    reason: str


class StructuredInsights(BaseModel):
    """Executive-grade structured output from the Insight Agent."""

    executive_summary: str = ""
    key_findings: List[str] = Field(default_factory=list)
    recommendations: List[str] = Field(default_factory=list)
    risks: List[str] = Field(default_factory=list)
    opportunities: List[str] = Field(default_factory=list)


class QueryResult(BaseModel):
    """The final, fully-rendered answer emitted by the agent pipeline."""

    question: str
    plan: ExecutionPlan
    validation: ValidationReport
    dataset_profile: Optional[DatasetProfile] = None
    tables: List[Dict[str, Any]] = Field(default_factory=list)
    charts: List[ChartSpec] = Field(default_factory=list)
    text: str = ""
    answer: Dict[str, Any] = Field(default_factory=dict)
    insight: str = ""
    recommendation: str = ""
    structured: StructuredInsights = Field(default_factory=StructuredInsights)
    confidence: float = 0.0
    follow_ups: List[FollowUp] = Field(default_factory=list)
    execution_time_ms: float = 0.0
    llm_mode: Literal["llm", "deterministic"] = "deterministic"
    created_at: str = ""


ExecutionPlan.model_rebuild()


# --------------------------------------------------------------------------- #
# API payloads
# --------------------------------------------------------------------------- #
class AnalyzeRequest(BaseModel):
    dataset_id: str
    question: str
    hints: Dict[str, Any] = Field(default_factory=dict)


class AnalyzeResponse(BaseModel):
    kind: Literal["answer", "clarification"] = "answer"
    result: Optional[QueryResult] = None
    clarification: Optional[ClarificationRequest] = None
    history_id: Optional[str] = None


class ClarificationRequest(BaseModel):
    question: str
    message: str
    options: List[ClarificationOption] = Field(default_factory=list)
